### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by tuxdotrs** [Mespyr/dotfiles#1]
Hello, I was unable to replicate this setup. I reviewed the configuration file, and it seems to be intended for a different setup. I'm searching for the configuration that is displayed in the screenshot.

Thank you.

**Comment by Mespyr** [comment]
I am so sorry, I haven't checked my dotfiles in a while. I've just been committing all of my new configs here for a bit without a thought. The image that was in the README was for a old config I have. You can look into the version history if you want to find it.
